<?php

declare(strict_types=1);

namespace vinyl\diTest\integration\testAsset\autoGeneratedProxyUsedAsConstructorArgument;

use stdClass;

class ClassA
{
    public stdClass $class;
    public array $arrayMap;
    public array $arrayList;

    public function __construct(stdClass $class, array $arrayMap, array $arrayList)
    {
        $this->class = $class;
        $this->arrayMap = $arrayMap;
        $this->arrayList = $arrayList;
    }
}
