name: Test Suite

on:
  - pull_request
  - push

jobs:
  run:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        php-versions: ['7.4']
    runs-on: ${{ matrix.operating-system }}
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        ini-values: zend.assertions=1, assert.exception=1
    
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Run Tests
      run: vendor/bin/phpunit --configuration phpunit.xml.dist
